---
apiVersion: "ran.openshift.io/v1"
kind: "SiteConfig"
metadata:
  name: "gitlab-test-cluster"
  namespace: "cluster-instance"
spec:
  baseDomain: "test.com"
  clusterImageSetNameRef: "cluste-img-1"
  sshPublicKey: "ssh hdhdghfghfghfghfghfg"
  pullSecretRef:
    name: "key-reference/"
  clusters:
  - clusterName: "gitlab-test-cluster"
    extraManifestPath: "/path"
    extraManifests:
      filter:
        inclusionDefault: "exclude"
        include:
        - "main.yaml"
    networkType: "OVNKubernetes"
    clusterLabels:
      test: "test"
    clusterNetwork:
    - cidr: "192.168.1.0/2"
      hostPrefix: 24
    machineNetwork:
    - cidr: "192.168.1.0/2"
    apiVIP: "192.168.1.0"
    ingressVIP: "192.168.1.0"
    serviceNetwork:
    - "10.0.0.0/24"
    additionalNTPSources:
    - "192.168.1.0"
    nodes:
    - hostName: ""
      role: "worker"
      bmcAddress: "192.168.65.3"
      bmcCredentialsName:
        name: "bmc-credentials-0"
      nodeLabels: {}
      bootMode: "UEFI"
      rootDeviceHints:
        vendor: "Red Hat VirtIO"
        deviceName: ""
        size: 0
      bootMACAddress: "AA:3F:92:1B:C4:7E"
      nodeNetwork:
        interfaces:
        - name: "ens1f0"
          macAddress: "04:32:01:52:74:70"
        - name: "ens1f1"
          macAddress: "04:32:01:52:74:71"
        - name: "ens2f0"
          macAddress: "C4:CB:E1:B5:89:01"
        config:
          interfaces:
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens1f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens1f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens2f0"
            state: "up"
            type: "ethernet"
            mtu: 75000
          dns-resolver:
            config:
              server: []
          routes:
            config:
            - next-hop-interface: ""
              destination: "0.0.0.0/0"
              next-hop-address: ""