---
apiVersion: "ran.openshift.io/v1"
kind: "SiteConfig"
metadata:
  name: "ankara-odine-cluster"
  namespace: "ankara-cluster-odine"
spec:
  baseDomain: "turkcell.tgc"
  clusterImageSetNameRef: "cluster-image-001"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD D1n8nRj0NfJfJ9pG0DzvN0DH7x+7rS5lVWZc0d0lTgLGH2YS0w0K5tBVkZD0g0KsO1j5zC2pF6VYi6Y0UjafvT3wGeHh7sM5aFpsdSvdF+7Iu4LThJrLb5Hn1m2FJ63pNzs4D9xmqPjR6i1WND0QTFVtM8rZ1yWRJbo5dNl1p3m7x3MpAmVQqxgR0K8sM5mU9Bz3o7ycYZttZ7a4g4mB9zZs1S8WwfkqU4Qdbp0x6Kps4pupmKL0k/cWuQsH5U/8LJbJwcE3kZ4HCxn/9dTGyPMQ6k2hCaqFAPvXOj5hXykRSPwuhD\
    \ dummy@example"
  pullSecretRef:
    name: "secret/pul-secrets"
  clusters:
  - clusterName: "ankara-odine-cluster"
    extraManifestPath: "path/odine/policies"
    extraManifests:
      filter:
        inclusionDefault: "exclude"
        include:
        - "anakra-policies.yaml"
    networkType: "OVNKubernetes"
    clusterLabels:
      location: "ankara"
    clusterNetwork:
    - cidr: "10.121.0.0/14"
      hostPrefix: 24
    machineNetwork:
    - cidr: "10.125.251.64/27"
    apiVIP: "10.125.251.73"
    ingressVIP: "10.125.251.72"
    serviceNetwork:
    - "172.30.0.0/16"
    additionalNTPSources:
    - "10.218.99.21"
    - "ntp.pool.org"
    nodes:
    - hostName: "odine.master.org"
      role: "master"
      bmcAddress: "192.168.65.3"
      bmcCredentialsName:
        name: "bmc-credentials-0"
      nodeLabels:
        storage: "zte"
      bootMode: "UEFISecureBoot"
      rootDeviceHints:
        vendor: "ZTE"
        deviceName: "/dev/sda"
        size: 90
      bootMACAddress: "AA:3F:92:1B:C4:7E"
      nodeNetwork:
        interfaces:
        - name: "ens1f0"
          macAddress: "04:32:01:52:74:70"
        - name: "ens1f1"
          macAddress: "04:32:01:52:74:71"
        - name: "ens2f0"
          macAddress: "C4:CB:E1:B5:89:01"
        config:
          interfaces:
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens1f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens1f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens2f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            link-aggregation:
              mode: "active-backup"
              port:
              - "ens1f0: 04:32:01:52:74:70"
              - "ens2f0: C4:CB:E1:B5:89:01"
              options:
                miimon: "100"
            ipv6:
              enabled: false
            name: "bond0"
            description: "bond"
            state: "up"
            type: "bond"
            mtu: 9000
          - vlan:
              base-iface: "bond0"
              id: 400
            ipv4:
              address:
                prefix-length: "16"
                ip: "10.10.55.124"
              enabled: true
            ipv6:
              enabled: false
            name: "bond0.400"
            state: "up"
            type: "vlan"
            mtu: 9000
          dns-resolver:
            config:
              server:
              - "8.8.8.8"
          routes:
            config:
            - next-hop-interface: "bond0.400"
              destination: "0.0.0.0/0"
              next-hop-address: "10.10.55.124"
    - hostName: "node.worker.org"
      role: "worker"
      bmcAddress: "172.16.180.19"
      bmcCredentialsName:
        name: "bmc-credentials-1"
      nodeLabels: {}
      bootMode: "UEFISecureBoot"
      rootDeviceHints:
        vendor: "ZTE"
        deviceName: "/dev/sdb"
        size: 90
      bootMACAddress: "5C:11:8A:EF:09:33"
      nodeNetwork:
        interfaces: []
        config:
          interfaces:
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "bond1"
            description: "bond1"
            state: "up"
            type: "bond"
            mtu: 9000
          - vlan:
              base-iface: "bond1"
              id: 401
            ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "bond1.401"
            state: "up"
            type: "vlan"
            mtu: 9000
          - vlan:
              base-iface: "bond1"
              id: 402
            ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "bond1.402"
            state: "up"
            type: "vlan"
            mtu: 9000
          dns-resolver:
            config:
              server:
              - "8.8.1.1"
          routes:
            config:
            - next-hop-interface: "bond1"
              destination: "0.0.0.0/0"
              next-hop-address: "10.10.55.124"